spring.application.name=grandparents

# База данных
spring.datasource.url=jdbc:mysql://localhost:3306/grandparents?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1707895
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===== MAX BOT (из тестового проекта) =====
max.bot.mode=webhook
max.bot.webhook.token=f9LHodD0cOKmGPin3BDo-hL_P3q9-caRpWOTOXHfTHWk8CN1Us-2UXzgAddfy_7gxFZUaEmWlv4QEGumY3HB
max.bot.webhook.url=https://curiously-cogent-sole.cloudpub.ru/webhook/max
max.bot.webhook.secret=my-very-secret-key