spring.application.name=grandparents

# Сервер
server.address=0.0.0.0
server.port=80        

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://pansal-ansbotmax-budimir66.db-msk0.amvera.tech:5432/grandparents?ssl=true&sslmode=require}
spring.datasource.username=${DB_USERNAME:Budimir}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Кэширование запросов
spring.jpa.properties.hibernate.cache.use_query_cache=true
spring.jpa.properties.hibernate.cache.use_second_level_cache=true

# MAX BOT
max.bot.mode=webhook
max.bot.webhook.token=${MAX_BOT_TOKEN}
max.bot.webhook.url=${MAX_BOT_WEBHOOK_URL}
max.bot.webhook.secret=${MAX_BOT_WEBHOOK_SECRET}

# Яндекс.Карты
yandex.maps.api.key=${YANDEX_MAPS_API_KEY}
yandex.maps.static.key=${YANDEX_MAPS_STATIC_KEY}

# Telegram
telegram.bot.token=${TELEGRAM_BOT_TOKEN}

# Увеличить таймауты
spring.mvc.async.request-timeout=60000


